version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

  api:
    build:
      context: .
    container_name: api-container
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    networks:
      - app-network
    restart: always
    command: ["sh", "-c", "wait-for-it mysql-container:3306 -- knex migrate:latest --env production && npm start"]

volumes:
  mysql-data:

networks:
  app-network:
    driver: bridge
